apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name}}
  labels: {{ include "common.labels" .| nindent 4}}
spec:
  selector:
    matchLabels: {{ include "common.labels" .| nindent 6}}
  serviceName: {{.Values.service.name}}
  replicas: {{ .Values.replicaCount}}
  template:
    metadata:
      labels: {{ include "common.labels" .| nindent 8}}
    spec:
      containers:
      - name: {{ .Release.Name}}
        image: {{.Values.image}}
        ports:
        - containerPort: {{.Values.ports.port}}
        volumeMounts:
        - name: kibana-configmap
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
      volumes:
      - name: kibana-configmap
        configMap:
          name: kibana-configmap
          