apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  namespace: elastic
spec:
  selector: {{ include "common.labels" .| nindent 4}}
  type: {{.Values.service.type}}
  ports:
    - name: {{.Values.service.name}}
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
      nodePort: {{.Values.service.nodePort}}