apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  type: {{ .Values.service.type}}
  selector: {{ include "common.labels" . | nindent 4 }}
  ports:
  - name: http
    port: {{.Values.ports.http}}
    targetPort: {{.Values.ports.http}}
