apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap 
data:
  logstash.conf: |
    input {
      tcp {
        host => "0.0.0.0"
        port => 5516
      }
    }
    filter {
      if ![fields][type] {
      mutate { add_field => { "[fields][type]" => "index" } }
      }
      if ![fields][region] {
      mutate { add_field => { "[fields][region]" => "vn" } }
      }
      if ![@metadata][beat] {
      mutate { add_field => { "[@metadata][beat]" => "axis" } }
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-svc:9200"]
        index => "%{[fields][region]}-%{[@metadata][beat]}-%{[fields][type]}-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }    
