apiVersion: v1
kind: Service
metadata:
  name: logstash-svc
  namespace: elastic
spec:
  type: NodePort
  ports:
    - port: 5516
      targetPort: 5516
      name: port1
      nodePort: 30516
  selector:
    app: logstash
